### ISSUE TITLE
handle.bin

### ISSUE THREAD

**Issue by meatrocket45** [ic3w0lf22/Roblox-Account-Manager#485]
Hi i just wanted to ask about the handle.bin file and why its encrypted?

![image](https://github.com/user-attachments/assets/8f43f3bc-7254-4a50-8bab-680c8e3339e7)

**Comment by ic3w0lf22** [comment]
it's not encrypted, it's an executable file used to find roblox's log file (eg: `C:\Users\...\AppData\Local\Roblox\logs\0.636.1.6360627_20000101T000000Z_Player_F0000_last.log`)

the file is renamed to a `.bin` file to prevent the user from launching it, and even deleting it because they saw a "random exe"

it is owned & distributed by microsoft: https://learn.microsoft.com/en-us/sysinternals/ https://learn.microsoft.com/en-us/sysinternals/downloads/handle
